services:
  app:
    container_name: graphql-app
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/graphql
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=4000
      - JWT_SECRET=12345
      - JWT_EXPIRES_IN=1h
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0
    container_name: graphql-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.4
    container_name: graphql-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
