services:
  app:
    container_name: graphql-app
    build: .
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/graphql
      - PORT=4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: graphql-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
